### ISSUE TITLE
Python3 tsz Error

### ISSUE THREAD

**Issue by garywu520** [trzsz/trzsz#28]
Python3 tsz comman Error
```
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/trzsz/iterm2/main.py", line 245, in main

    download_files(args, loop, session)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/trzsz/iterm2/main.py", line 80, in download_files

    send_action(True, __version__)

TypeError: send_action() missing 1 required positional argument: 'remote_is_windows'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/trzsz-iterm2", line 8, in <module>

    sys.exit(main())

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/trzsz/iterm2/main.py", line 252, in main

    fail_exit(e, False)

NameError: name 'fail_exit' is not defined
```

**Comment by lonnywong** [comment]
卸载之后重新安装一下吧，看来是依赖的 trzsz-libs 和 trzsz-iterm2 版本不同。
