### ISSUE TITLE
tsz Error

### ISSUE THREAD

**Issue by aijianiula0601** [trzsz/trzsz#29]
I got error like this. How to slove it?

Traceback (most recent call last):
  File "/home/huangjiahong.dracu/.local/bin/tsz", line 8, in <module>
    sys.exit(main())
  File "/home/huangjiahong.dracu/.local/lib/python3.5/site-packages/trzsz/svr/send.py", line 56, in main
    file_list = check_paths_readable(args.file, args.directory)
NameError: name 'check_paths_readable' is not defined

**Comment by lonnywong** [comment]
https://github.com/trzsz/trzsz/issues/28#issuecomment-1303254298

uninstall first, then reinstall should fix it.
