### ISSUE TITLE
trzsz.libs.utils.TrzszError: [TrzszError] colon: eJwBAAD//wAAAAE=

### ISSUE THREAD

**Issue by jue-jue-zi** [trzsz/trzsz#46]
```
::TRZSZGO:TRANSFER:R:1.1.3:9572589672900
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/svr/recv.py", line 128, in main
    recv_files(args, dest_path)
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/svr/recv.py", line 79, in recv_files
    local_list = transfer.recv_files(dest_path, None)
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/libs/transfer.py", line 358, in recv_files
    num = recv_file_num(callback)
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/libs/transfer.py", line 229, in recv_file_num
    num = utils.recv_integer('NUM')
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/libs/utils.py", line 452, in recv_integer
    return int(recv_check(typ, may_has_junk))
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/libs/utils.py", line 443, in recv_check
    raise TrzszError(buf, typ)
trzsz.libs.utils.TrzszError: [TrzszError] colon: eJwBAAD//wAAAAE=
goroutine 69 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/trzsz/trzsz-go/trzsz.newTrzszError({0x140000c0020, 0x10}, {0x1047c9c83, 0x5}, 0x1)
        github.com/trzsz/trzsz-go@v1.1.6-0.20230819142016-6c37e8d0a49b/trzsz/comm.go:232 +0x22c
github.com/trzsz/trzsz-go/trzsz.(*trzszTransfer).recvCheck(0x104883f60?, {0x1047c95f4, 0x3}, 0x0?, 0x140000a40a0?)
        github.com/trzsz/trzsz-go@v1.1.6-0.20230819142016-6c37e8d0a49b/trzsz/transfer.go:315 +0x184
github.com/trzsz/trzsz-go/trzsz.(*trzszTransfer).recvString(0x100000000?, {0x1047c95f4?, 0x0?}, 0xc0?, 0x0?)
        github.com/trzsz/trzsz-go@v1.1.6-0.20230819142016-6c37e8d0a49b/trzsz/transfer.go:355 +0x20
github.com/trzsz/trzsz-go/trzsz.(*trzszTransfer).recvConfig(0x140002922c0)
        github.com/trzsz/trzsz-go@v1.1.6-0.20230819142016-6c37e8d0a49b/trzsz/transfer.go:533 +0x60
github.com/trzsz/trzsz-go/trzsz.(*TrzszFilter).uploadFiles(0x1400010b2b0, 0x1?, 0x0?)
        github.com/trzsz/trzsz-go@v1.1.6-0.20230819142016-6c37e8d0a49b/trzsz/filter.go:346 +0xe8
github.com/trzsz/trzsz-go/trzsz.(*TrzszFilter).handleTrzsz(0x1400010b2b0, 0x52)
        github.com/trzsz/trzsz-go@v1.1.6-0.20230819142016-6c37e8d0a49b/trzsz/filter.go:388 +0x298
created by github.com/trzsz/trzsz-go/trzsz.(*TrzszFilter).wrapOutput in goroutine 8
        github.com/trzsz/trzsz-go@v1.1.6-0.20230819142016-6c37e8d0a49b/trzsz/filter.go:608 +0x3d0
```

**Comment by lonnywong** [comment]
弄点详细的日志出来看看：
```sh
trzsz -t ssh xxx   # 登录

echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'

# 你会看到输出一个本地电脑的日志路径

trz

# 出错后
echo -e '<DISABLE_TRZSZ_TRACE_LOG\x3E'
```

然后发那个日志内容出来看看，也可发到我的邮箱 lonnywong@qq.com

**Comment by jue-jue-zi** [comment]
我是使用tssh登陆的开发机，然后开了tmux ssh连了一台远程的机器，执行 `echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'` 直接返回：<ENABLE_TRZSZ_TRACE_LOG> 没有日志路径

**Comment by jue-jue-zi** [comment]
如果我在tmux中使用 `trzsz -t ssh` 命令替代 `ssh` 命令连接到远程机器，再在远程机器执行 `trz` 会出错

```
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/svr/recv.py", line 128, in main
    recv_files(args, dest_path)
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/svr/recv.py", line 64, in recv_files
    action = transfer.recv_action()
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/libs/transfer.py", line 49, in recv_action
    action = utils.recv_json('ACT')
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/libs/utils.py", line 553, in recv_json
    dic = recv_string(typ, may_has_junk)
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/libs/utils.py", line 468, in recv_string
    return decode_buffer(recv_check(typ, may_has_junk)).decode('utf8')
  File "/root/.local/pipx/venvs/trzsz/lib64/python3.8/site-packages/trzsz/libs/utils.py", line 443, in recv_check
    raise TrzszError(buf, typ)
trzsz.libs.utils.TrzszError: exec: "zenity": executable file not found in $PATH
```

**Comment by jue-jue-zi** [comment]
仔细看了一下文档，在 tmux 中执行 `trzsz -r ssh` 登陆后在远程机器可以正常传输了，谢谢

**Comment by lonnywong** [comment]
建议用 `tssh` 代替 `trzsz -r ssh`，即用两次 tssh ，第二个 tssh 会自动扮演 `trzsz -r ssh` 的角色。
