### ISSUE TITLE
iTerm2下trz选择文件后报错

### ISSUE THREAD

**Issue by hyperlau** [trzsz/trzsz#57]
环境：
Local:MacOS 10.15.7
Remote:Armbian-unofficial 24.5.0-trunk Noble

trz执行后报错：

    Traceback (most recent call last):

      File "/usr/local/Cellar/trzsz/1.1.2/libexec/lib/python3.11/site-packages/trzsz/iterm2/main.py", line 359, in main

        upload_files(args, loop, connection, session, False, remote_is_windows)

      File "/usr/local/Cellar/trzsz/1.1.2/libexec/lib/python3.11/site-packages/trzsz/iterm2/main.py", line 172, in upload_files

        config = recv_config()

                 ^^^^^^^^^^^^^

      File "/usr/local/Cellar/trzsz/1.1.2/libexec/lib/python3.11/site-packages/trzsz/libs/utils.py", line 476, in recv_config

        config = recv_json('CFG', True)

                 ^^^^^^^^^^^^^^^^^^^^^^

      File "/usr/local/Cellar/trzsz/1.1.2/libexec/lib/python3.11/site-packages/trzsz/libs/utils.py", line 430, in recv_json

        dic = recv_string(typ, may_has_junk)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/usr/local/Cellar/trzsz/1.1.2/libexec/lib/python3.11/site-packages/trzsz/libs/utils.py", line 355, in recv_string

        return decode_buffer(recv_check(typ, may_has_junk)).decode('utf8')

                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/usr/local/Cellar/trzsz/1.1.2/libexec/lib/python3.11/site-packages/trzsz/libs/utils.py", line 335, in recv_check

        raise TrzszError(buf, typ)

    trzsz.libs.utils.TrzszError: [TrzszError] ]134;: %autopoll 3MHG8dZFu1CMWD1uSQ\$begin ps

**Comment by lonnywong** [comment]
先升级一下 trzsz 看看

**Comment by lonnywong** [comment]
请参考 https://github.com/trzsz/trzsz/issues/60#issuecomment-2455361520

**Comment by hyperlau** [comment]
感谢 我试试
________________________________
发件人: Lonny Wong ***@***.***>
发送时间: Monday, November 4, 2024 11:02:53 AM
收件人: trzsz/trzsz ***@***.***>
抄送: hyperlau ***@***.***>; Manual ***@***.***>
主题: Re: [trzsz/trzsz] iTerm2下trz选择文件后报错 (Issue #57)


请参考 #60 (comment)<https://github.com/trzsz/trzsz/issues/60#issuecomment-2455361520>

―
