### ISSUE TITLE
trzsz.libs.utils.TrzszError: [TrzszError] end: : Resource temporarily unavailable

### ISSUE THREAD

**Issue by R-16Bob** [trzsz/trzsz#58]
在本地向服务器传输文件时，传输较小文件可以正常使用；但传输较大文件(28M)时总是传输到一半就报错停止。我想知道是否有方法解决这个问题。
报错信息如下：
```::TRZSZGO:TRANSFER:R:1.1.5:2500371109700
Traceback (most recent call last):
  File "/home/ebd_2/all/anaconda3/lib/python3.11/site-packages/trzsz/svr/recv.py", line 128, in main
    recv_files(args, dest_path)
  File "/home/ebd_2/all/anaconda3/lib/python3.11/site-packages/trzsz/svr/recv.py", line 79, in recv_files
    local_list = transfer.recv_files(dest_path, None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ebd_2/all/anaconda3/lib/python3.11/site-packages/trzsz/libs/transfer.py", line 388, in recv_files
    md5 = recv_file_data(file, size, callback)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ebd_2/all/anaconda3/lib/python3.11/site-packages/trzsz/libs/transfer.py", line 351, in recv_file_data
    data = utils.recv_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/ebd_2/all/anaconda3/lib/python3.11/site-packages/trzsz/libs/utils.py", line 550, in recv_data
    return recv_binary('DATA')
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ebd_2/all/anaconda3/lib/python3.11/site-packages/trzsz/libs/utils.py", line 493, in recv_binary
    return decode_buffer(recv_check(typ, may_has_junk))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ebd_2/all/anaconda3/lib/python3.11/site-packages/trzsz/libs/utils.py", line 454, in recv_check
    raise TrzszError(buf, typ)
trzsz.libs.utils.TrzszError: [TrzszError] end: : Resource temporarily unavailable```

**Comment by lonnywong** [comment]
看起来是你的源文件有问题，不能正常被读取完，所以报错 `Resource temporarily unavailable`。

**Comment by R-16Bob** [comment]
感谢回复，我使用rz成功传输了，虽然不知道为什么用trz只能传一半。

**Comment by lonnywong** [comment]
你可以用 go 版 trzsz 试试：https://github.com/trzsz/trzsz-go 客户端可以用 https://github.com/trzsz/trzsz-ssh
