### ISSUE TITLE
Iterm2 中 trzsz.libs.utils.TrzszError: [TrzszError] ]134;: %autopoll 2n7FfeHlp4ofOfxUd5\$begin ps

### ISSUE THREAD

**Issue by librola** [trzsz/trzsz#60]
如题，当我在 iTerm2 用一个 ssh 的 profile 打开了新窗口，则当运行 `trz` 时会出现下面的错误：

![QQ_1730730601914](https://github.com/user-attachments/assets/f7c5f3b5-3808-49a2-93c0-cb0d3acdae75)

完整的错误内容如下：

```
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/trzsz/1.1.5/libexec/lib/python3.13/site-packages/trzsz/iterm2/main.py", line 388, in main

    upload_files(args, loop, connection, session, False, remote_is_windows)

    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/trzsz/1.1.5/libexec/lib/python3.13/site-packages/trzsz/iterm2/main.py", line 190, in upload_files

    config = transfer.recv_config()

  File "/opt/homebrew/Cellar/trzsz/1.1.5/libexec/lib/python3.13/site-packages/trzsz/libs/transfer.py", line 81, in recv_config

    config = utils.recv_json('CFG', True)

  File "/opt/homebrew/Cellar/trzsz/1.1.5/libexec/lib/python3.13/site-packages/trzsz/libs/utils.py", line 564, in recv_json

    dic = recv_string(typ, may_has_junk)

  File "/opt/homebrew/Cellar/trzsz/1.1.5/libexec/lib/python3.13/site-packages/trzsz/libs/utils.py", line 479, in recv_string

    return decode_buffer(recv_check(typ, may_has_junk)).decode('utf8')

                         ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/trzsz/1.1.5/libexec/lib/python3.13/site-packages/trzsz/libs/utils.py", line 454, in recv_check

    raise TrzszError(buf, typ)

trzsz.libs.utils.TrzszError: [TrzszError] ]134;: %autopoll 17vMT7QpWxG87gxkJf\$begin ps
```

但是，如果我直接在我本地的 default profile 中使用 `ssh user@server` 这样连接，并且由 iTerm2 自动切换到这个 profile 时，就可以正常使用 `trz`，没有出现报错。 

---

trzsz-iterm2 (trzsz) py 1.1.5
iTerm2 Build 3.5.6

---

iTerm2 中的配置：

![QQ_1730730838746](https://github.com/user-attachments/assets/6bd4d155-ad8c-4882-9290-043b5d32cb96)

**Comment by lonnywong** [comment]
不知是哪里输出 %autopoll 这段内容导致的

**Comment by librola** [comment]
还有好像如果我在用一个 ssh 的 profile 打开了的窗口中，再用 `tmux -CC` 打开一个 tmux 集成的窗口，在这个窗口中 `trz` 也是可以正常运行的，好像就只有用 ssh 的 profile 打开窗口之后直接 `trz` 会出问题。

我这边两台远程主机都可以复现。

**Comment by lonnywong** [comment]
`tmux -CC` 是我专门适配了的。你说的有问题的用法，我不是很了解，没这么用过。

**Comment by librola** [comment]
谢谢您，我大概知道了，应该是 iTerm2 的 [SSH Integration](https://gitlab.com/gnachman/iterm2/-/wikis/SSH-Integration) 的锅。

![image](https://gitlab.com/gnachman/iterm2/-/wikis/uploads/f9a1ecfde909a271f4d62d5722c0337a/image.png)

像这样配置 ssh 会默认开启 SSH Integration，而 Iterm2 会因此用它自己的 `it2ssh` 代替系统的 `ssh` 命令。这个 `it2ssh` 会在交互的过程中额外发送一些 iTerm2 使用的元数据，似乎是这个影响了 `trzsz` 的数据流。

把 SSH Integration 关闭就没有问题了。

#57 应该是和我一样的失败原因。
